### ISSUE TITLE
Parsing for dungeon data

### ISSUE THREAD

**Issue by rohilthopu** [nachoapps/rpad-cogs-utils#30]
Hey t_r,

I have some of the dungeon data parsed and was gonna check with you before I submitted a PR for it. I thought it might take some of the load off of you a bit, since I am using your API after all. 

Would it be helpful at all?

-Rohil

**Comment by nachoapps** [comment]
Yeah! I actually have some time to work on dungeon stuff, I'm about to start on a scraper for the dungeon contents.

Did you put together something for enemy skills, or is it for the various dungeon parameters? Either is fine, although enemy skills will become more important shortly, I think the dungeon parameters is interesting but not critical for populating DadGuide with the data.

**Comment by rohilthopu** [comment]
I have some parsing done for dungeon/floor parameters such as drops and their rarities, entry requirements, basic stuff like battles, stam, etc (That you just added in), and im working on parsing modifiers (like god type all stats 1.5x and what not).

I honestly had no idea where to start for the enemy skills. Have you found anything out in terms of those? If so, I'd love to help in any way I can now that work has slowed down hard lol.

**Comment by nachoapps** [comment]
Merged in, thanks!
